services:
  - type: web
    name: searchapi
    runtime: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/searchapi-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: searchapidb
          property: connectionString
    plan: free

databases:
  - name: searchapidb
    databaseName: searchapi
    user: searchapi
    plan: free
    ipAllowList: [] 