services:
  - type: web
    name: searchapi
    env: docker
    buildCommand: ./mvnw clean package
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: searchapidb
          property: connectionString
        transform: "jdbc:${value}"
      - key: DATABASE_USERNAME
        fromDatabase:
          name: searchapidb
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: searchapidb
          property: password
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    plan: free

databases:
  - name: searchapidb
    databaseName: searchapi
    user: searchapi
    plan: free
    ipAllowList: [] 